---
title: "Activities"
editor: visual
---

------------------------------------------------------------------------

**QWSG ID Days & Count Dates**

**Wader ID Days**

Dates:

Sunday 1 June 2025 – Manly Boat Harbour (restricted area)

Saturday 14 June 2025 – Lytton Claypan (restricted area)

Sunday 12 October 2025 – Manly Boat Harbour (restricted area)

Saturday 29 November 2025 – Lytton Claypan (restricted area)

**Manly Boat Harbour** (restricted area) Sunday 1 June 2025 1.67m high tide at 1:45pm. Meeting time 1:00pm. We’ll be there at high tide, hoping to find Double-banded Plovers visiting from New Zealand, as well as other waders that have decided not to fly north this year. The sun will be little behind us for good viewing

Sunday 12 October 2025 2.33m high tide at 1:27pm. Meeting time 2:00pm. We’ll be there at high tide, hoping to see a good range of waders. It’s an ideal site for beginners as the birds are generally quite close, and you won’t have to walk through any mud. The sun will be little behind us which should be good viewing. These dates give a good opportunity to access this site, which is normally closed to the public.

Under our access agreement with the State strict conditions apply. Participants will be required to sign a form acknowledging responsibility for their own health and safety, including: wearing protective clothing at all times (e.g. hat, shoes, sunglasses) and using sunscreen drinking water to avoid dehydration using insect repellent if necessary telling a group leader about any health issues that may affect taking part in the field trip if feeling unwell, or concerned about someone else being unwell, immediately telling a group leader or another participant immediately telling a group leader or another participant about any injury suffered (including a slip, trip, fall and snake bite) or hazard that may cause injury to someone. Participants must wear enclosed footwear, have drinking water, and a jacket is advisable because of the likelihood of a westerly wind. The gate will be locked after we enter, and it will not be possible for late arrivals to participate. Meet at the end of Davenport Drive Manly. Bring binoculars, telescopes if you have one, drinking water and insect repellent. There are no public toilets at this site. Please arrive on time for our preliminary chat. You’ll need to be a BQ or QWSG member to attend. Hopefully we’ll be able to identify all the birds and answer all your questions. Contact Gary Kane on 0412 423 023 to register, and for more details. Participation will be strictly limited to people with confirmed registrations.

------------------------------------------------------------------------

**Lytton Claypan** (restricted area) Saturday 14 June 2025 1.77m high tide at 11:13am. Meeting time 10:00am. Saturday 29 November 2025 2.15m high tide at 4:01pm. Meeting time 3:30pm. We’ll be there at high tide, hoping to see a good range of waders. Be aware there will be some walking involved, and the site can be a bit muddy. However, the sun should be low for good viewing.

This is a Port of Brisbane site, and permission will be sought before conducting the event. Meet in the car park of the Port of Brisbane Boat Ramp, off Port Drive. This is just to the south and east of the bridge that connects Lytton to the Port of Brisbane. see link: where to meet. Bring binoculars, telescopes if you have one, drinking water, insect repellent, and boots suitable for a bit of mud. There are public toilets in the car park. Please arrive on time for our preliminary chat. You’ll need to be a BQ or QWSG member to attend, see link: become a member. Hopefully we’ll be able to identify all the birds and answer all your questions. Contact Gary Kane on 0412 423 023 to register, and for more details. Participation will be strictly limited to people with confirmed registrations.

**Count Dates 2025**

The following list of dates gives the scheduled QWSG count dates and also the Port of Brisbane count dates. If you want to be involved in regular counts or would like to come along and see how a count is conducted, please contact our Count Coordinator (see the Contact Us page). Please note that due to insurance reasons we are not always able to include new people in counts straight away, particularly in areas like the Port of Brisbane which are working sites where we operate under contract. However, we are always looking for new counters so please do get in touch if you are interested in getting involved and helping us out. At the moment we really need new counters so if you think you can make the commitment to a count every month, or to just help out an existing counter please contact us, see the contact page for the count coordinator’s contact details.

**QWSG High Tide Monthly Count Program 2025**

NO COUNT IN JUNE

Sat 12 Jul 1.83m at 10:19 National Winter Count

Sat 16 Aug 2.11m at 15:07

Sat 27 Sep 2.08m at 12:32

Sat 25 Oct 2.25m at 11:29

Sat 22 Nov 2.37m at 10:35

Sat 20 Dec 2.43m at 09:45

Counters Rockhampton and north – please select a date as close as possible to the count programme Sat day with suitable tides to enable you to complete your counts.

**Port of Brisbane Count Dates 2025**

NO COUNT IN JUNE

Sun 13 Jul 1.86m at 11:03 Meet 09:45 National Winter Count

Sun 17 Aug 2.15m at 16:25 Meet 15:10

Sun 28 Sep 2.01m at 13:15 Meet 12:00

Sun 26 Oct 2.19m at 12:04 Meet 10:50

Sun 23 Nov 2.34m at 11:10 Meet 09:50

Sun 21 Dec 2.43m at 10:21 Meet 09:00
