---
title: "News_and_Notices"
editor: visual
---

QUEENSLAND WADER STUDY GROUP (QWSG) A Special Interest Group of the Queensland Ornithological Society Inc.

POSITION STATEMENT ON THE RAMSAR CONVENTION AND A PROPOSAL TO BUILD A RESIDENTIAL AND RETAIL DEVELOPMENT OVER INTERTIDAL MUDFLATS AT TOONDAH HARBOUR, MORETON BAY, QUEENSLAND. Dated: 22 July, 2021

The QWSG calls on the Australian Federal Government, the Queensland State Government and the Redland City Council to respect obligations to protect internationally recognised wetlands at Toondah Harbour in Moreton Bay under the Ramsar Convention. Australia became a signatory to the Ramsar Convention fifty years ago in 1971. The proposal to develop a residential and retail complex over intertidal mudflats to the north of the existing Stradbroke Island Ferry terminal will, if it proceeds, extinguish part of the Moreton Bay Ramsar site. Should it proceed, its lengthy construction period will disturb a wider area of Moreton Bay marine environment. QWSG recognises that the existing ferry terminal needsrenewal to support the economic and social advancement of North Stradbroke Island and supports appropriate and environmentally sound develop of the ferry terminal and its links to the island. QWSG does not support the current proposed develop that extends well beyond the terminal site to extinguish approximately 44 hectares of marine coastal habitat. Australia became a signatory to the Ramsar Convention in 1971 and has remained a supporter of international obligations under the Convention with more that seventy Australian wetlands registered by Australia under the Convention. QWSG notes that in recent years two development applications submitted to the Commonwealth under the EPBC Act (1999) that would have impacted upon Australian coastal Ramsar sites have been declined by the Federal Minister for the Environment – the first at Turtle Cove on the Queensland Fraser Coast and the second adjacent to the Ramsar site at Eighty-mile Beach in Western Australia. QWSG welcomes the decisions of the Minister for the Environment to protect the coastal habitats for migratory shorebirds in these international-recognised important areas.
